"""Add email field to Employee model

Revision ID: b40152318760
Revises: 
Create Date: 2025-07-05 07:58:15.106979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b40152318760'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if email column exists before adding it
    from sqlalchemy.engine.reflection import Inspector
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('employees')]
    
    if 'email' not in columns:
        op.add_column('employees', sa.Column('email', sa.String(length=100), nullable=True))
        op.create_unique_constraint(None, 'employees', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'email')
    # ### end Alembic commands ###
